name: Build Mobile App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up matrix
        run: echo "starting...."
  build:
    needs: prepare
    strategy:
      matrix:
        include:
          - platform: android
            runner: ubuntu-latest
            folder-id: https://drive.google.com/drive/folders/1NHG4yH-LMXwBnvgmwDnYKWdoIizfh3Ed
            framework-path: ./weshd/android/
            build-cmd: eas build --local --non-interactive --output=./app-build/app.apk --platform=android --profile androidAPK
          - platform: ios
            runner: macos-latest
            folder-id: https://drive.google.com/drive/folders/1UiIZ913lh_mrv7oKnI_u9418b5m8xttl
            framework-path: ./weshd/ios/
            build-cmd: eas build --local --non-interactive --output=./app-build/app.ipa --platform=ios
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 18

      - name: Fix gitignore
        run: node ./cmd/fix-app-build.js

      - name: Fix package.json
        run: yarn remove @lottiefiles/react-lottie-player

      - name: Install node modules
        run: yarn install

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Download frameworks
        run: |
          pip install gdown
          gdown ${{matrix.folder-id}} -O ${{matrix.framework-path}} --folder

      - name: Prebuild
        run: npx expo prebuild --clean

      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.build-cmd }}

      - name: Upload apk
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'android'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}
          path: app-build/app.apk
          if-no-files-found: error

      - name: Upload ipa
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ios'
        with:
          name: teritori-${{ github.sha }}-${{ matrix.os }}
          path: app-build/app.ipa
          if-no-files-found: error

      - name: EAS Submit iOS IPA
        if: matrix.os == 'ios'
        run: eas submit --platform=ios --path=./app.ipa
